server:
  servlet:
    context-path: /forum

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community
    username: root
    password: +-11WDwd
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      stat-view-servlet:
        enabled: true
        login-username: wuui
        loginPassword: +-11WDwd
        url-pattern: /druid/*

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      aop-patterns: com.wuui.admin.*

      filters: stat,slf4j,wall

      filter:
        stat:
          enabled: true
          slow-sql-millis: 1000
          log-slow-sql: true

        wall:
          enabled: true
          config:

  thymeleaf:
    prefix: classpath:/templates/

#  redis:
#    host: r-uf6yexhvjqmg2y7zvmpd.redis.rds.aliyuncs.com
#    password: +-11WDwd
#    port: 6379

mybatis-plus:
  #  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.wuui.community.bean

#actuator指标监控
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

  endpoint:
    beans:
      enabled: true
    #显示应用程序运行状况信息
    health:
      enabled: true
      show-details: always
    #显示应用程序的相关信息
    metrics:
      enabled: true

    info:
      enabled: true
