server:
  servlet:
    context-path:

#配置community域名、上传文件路径
community:
  path:
    domain: http://localhost:8080
    upload: E:/Graduate/Java/Java_Project/Forum/upload

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      stat-view-servlet:
        enabled: true
        login-username: wuui
        loginPassword: 
        url-pattern: /druid/*

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      aop-patterns: com.wuui.admin.*

      filters: stat,slf4j,wall

      filter:
        stat:
          enabled: true
          slow-sql-millis: 1000
          log-slow-sql: true

        wall:
          enabled: true
          config:

  thymeleaf:
    prefix: classpath:/templates/

#  邮件配置: MailProperties
  mail:
    host: smtp.163.com
    port: 465
    username: 
    #需要到申请授权码
    password: 
    protocol: smtps
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  #  Redis配置
  redis:
    host: localhost
    port: 6379
    database: 1
#  kafka配置
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
# elasticsearch配置
#  data:
#    elasticsearch:
#      cluster-name: Dreamy-dream
#      cluster-nodes: 127.0.0.1:9300
  elasticsearch:
    uris: 127.0.0.1:9200 #要使用9200,9300废弃不使用

# TaskExecutionProperties
  task:
    execution:
      pool:
        core-size: 5
        max-size: 15
        queue-capacity: 100
# TaskSchedulingProperties
    scheduling:
      pool:
        size: 5
# quartz 配置
  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5



#mybatis-plus配置：
mybatis-plus:
  #  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wuui.community.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

# qiniu-oss
qiniu:
  key:
    access: 
    secret: 
  bucket:
    header:
      name: dee-forum-header
      url: http://rcy54cb1v.hd-bkt.clouddn.com


# caffeine配置
caffeine:
  posts:
    max-size: 15
    expire-seconds: 180


#actuator指标监控
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

  endpoint:
    # 程序所有的bean
    beans:
      enabled: true
    #显示应用程序运行状况信息
    health:
      enabled: true
      show-details: always
    #显示应用程序的相关信息
    metrics:
      enabled: true
    #显示应用程序信息
    info:
      enabled: true
    #暴露可用的缓存
    caches:
      enabled: true



